import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Brand from '@/components/Brand'
import ReminderTurn from '@/components/MedicalTurn/ReminderTurn'
import ActiveRecipe from '@/components/Recipe/ActiveRecipe'
import Headline from '@/components/Headline'
import Calendar from '@/components/Calendar'
import ModalNoAuth from '@/components/ModalNoAuth'
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography'
import styled from 'styled-components'

const ChildrenHeadlineTurn = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  & :nth-child(1) {
    grid-column: 1/-1;
    grid-row: 1/2;
  }
  & :nth-child(1) {
    grid-row: 2/3;
  }
  & :nth-child(1) {
    grid-row: 2/3;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Brand />
      </nav>
      <main className={styles.main}>
        <Headline Icon={Calendar} text={"Turnos proximo"}>
          <ChildrenHeadlineTurn>
            <Button variant="contained"> SACAR TURNO</Button>
            <Button variant="contained"> POSPONER</Button>
            <Button variant="contained"> CANCELAR</Button>
          </ChildrenHeadlineTurn>
        </Headline>
        <section className={styles.items}>
          <ReminderTurn 
          affair={"Vacunacion"} day={1} month="ENR" year={2012} initialTime={{hour: 12, minutes: 55}} endTime={{hour: 12, minutes: 55}}/>
          <ReminderTurn 
          affair={"Vacunacion"} day={1} month="ENR" year={2012} initialTime={{hour: 12, minutes: 55}} endTime={{hour: 12, minutes: 55}}/>
          <ReminderTurn 
          affair={"Vacunacion"} day={1} month="ENR" year={2012} initialTime={{hour: 12, minutes: 55}} endTime={{hour: 12, minutes: 55}}/>
        </section>
        <Headline Icon={Calendar} text={"Medicamentos activos"}>
          <Typography variant="body2">Ultima actualizacion: 12/02/2023</Typography>
        </Headline>
        <section className={styles.items}>
          <ActiveRecipe pet={"Simon"} durationInDays={1} units={2} lapse={3} medicament={"Ketamina"}/>
        </section>
      </main>
    </>
  )
}
